// pages/share.tsx
import React, { useState } from 'react';

const SharePage: React.FC = () => {
  const [shareItems] = useState([
    {
      id: 1,
      author: '张小明',
      avatar: '张',
      content: '今天天气真好，在公园里散步，感受春天的气息！🌸',
      imageUrl: 'https://picsum.photos/seed/share1/600/400.jpg',
      likes: 23,
      comments: 5,
      shares: 2,
      createdAt: '2小时前'
    },
    {
      id: 2,
      author: '李小红',
      avatar: '李',
      content: '周末去了趟郊外，发现了一家很棒的咖啡店，推荐给大家！☕ 环境很宜人，适合工作学习~ 📚',
      imageUrl: 'https://picsum.photos/seed/share2/600/400.jpg',
      likes: 45,
      comments: 12,
      shares: 8,
      createdAt: '3小时前'
    },
    {
      id: 3,
      author: '王大伟',
      avatar: '王',
      content: '刚完成一个有挑战性的项目，虽然过程很辛苦，但收获满满！感谢团队的支持和信任！💪',
      imageUrl: 'https://picsum.photos/seed/share3/600/400.jpg',
      likes: 88,
      comments: 23,
      shares: 15,
      createdAt: '4小时前'
    }
  ]);

  const commonEmojis = ['😊', '😂', '❤️', '👍', '🎉', '🔥', '💯', '🎁', '🌟', '✨', '🎨', '🎭'];

  return (
    <div className="min-h-screen" style={{ backgroundColor: 'var(--renren-bg)' }}>
      <header className="bg-white border-b border-gray-200" style={{ borderColor: 'var(--renren-border)' }}>
        <div className="max-w-6xl mx-auto p-4">
          <div className="flex items-center space-x-4">
            <a href="/" className="text-blue-600 hover:text-blue-800 font-medium">
              ← 返回首页
            </a>
            <h1 className="text-2xl font-bold" style={{ color: '#111827' }}>
              🔄 分享新鲜事
            </h1>
            <div className="flex items-center space-x-4">
              <span className="text-sm text-gray-500">{shareItems.length} 条分享</span>
              <select className="px-3 py-2 border border-gray-200 rounded-lg" style={{ borderColor: 'var(--renren-border)' }}>
                <option value="all">全部</option>
                <option value="life">生活</option>
                <option value="work">工作</option>
                <option value="study">学习</option>
              </select>
            </div>
          </div>
        </div>
      </header>

      <div className="max-w-6xl mx-auto p-4">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-1">
            <div className="bg-white rounded-lg border border-gray-200 p-6">
              <div className="text-lg font-semibold mb-4" style={{ color: '#111827' }}>
                发布新鲜事
              </div>
              <div className="space-y-4">
                <input
                  type="text"
                  placeholder="标题"
                  className="w-full p-3 border rounded-lg"
                  style={{ borderColor: 'var(--renren-border)' }}
                />
                <textarea
                  placeholder="分享你的新鲜事..."
                  className="w-full p-3 border rounded-lg resize-none"
                  style={{ borderColor: 'var(--renren-border)' }}
                  rows={4}
                />
                <div className="flex items-center space-x-2">
                  <input
                    type="text"
                    placeholder="图片URL(可选)"
                    className="flex-1 p-3 border rounded-lg"
                    style={{ borderColor: 'var(--renren-border)' }}
                  />
                  <select className="px-3 py-2 border rounded-lg" style={{ borderColor: 'var(--renren-border)' }}>
                    <option value="text">文字</option>
                    <option value="image">图片</option>
                    <option value="video">视频</option>
                    <option value="link">链接</option>
                  </select>
                </div>
                
                <div className="flex items-center space-x-2">
                  <span className="text-sm text-gray-600">类型：</span>
                  <select className="px-3 py-2 border rounded-lg" style={{ borderColor: 'var(--renren-border)' }}>
                    <option value="life">生活</option>
                    <option value="work">工作</option>
                    <option value="study">学习</option>
                  </select>
                </div>
                
                <div>
                  <div className="text-sm text-gray-600 mb-2">添加表情符号：</div>
                  <div className="grid grid-cols-8 gap-2">
                    {commonEmojis.map((emoji, index) => (
                      <button
                        key={index}
                        type="button"
                        className="p-2 hover:bg-gray-100 rounded text-lg transition-colors"
                      >
                        {emoji}
                      </button>
                    ))}
                  </div>
                </div>
                
                <div className="flex justify-between items-center">
                  <span className="text-sm text-gray-500">0/500</span>
                  <button className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white font-medium">
                    发布分享
                  </button>
                </div>
              </div>
            </div>
          </div>

          <div className="lg:col-span-2">
            <div className="space-y-4">
              <h2 className="text-xl font-bold mb-6" style={{ color: '#111827' }}>
                最新分享
              </h2>
              <div className="space-y-4">
                {shareItems.map((item) => (
                  <div key={item.id} className="bg-white rounded-lg border border-gray-200 p-6">
                    <div className="flex items-start space-x-3">
                      <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-blue-600 text-white rounded-full flex items-center justify-center font-bold">
                        {item.avatar}
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center space-x-2 mb-1">
                          <h4 className="font-semibold">{item.author}</h4>
                          <span className="text-sm text-gray-500">{item.createdAt}</span>
                        </div>
                      </div>
                    </div>
                    
                    {item.imageUrl && (
                      <div className="w-full h-48 rounded-lg overflow-hidden mb-3">
                        <img 
                          src={item.imageUrl} 
                          alt={item.content}
                          className="w-full h-full object-cover"
                        />
                      </div>
                    )}
                    
                    <p className="text-gray-800 leading-relaxed mb-4">
                      {item.content}
                    </p>
                    
                    <div className="flex items-center space-x-6">
                      <button className="flex items-center space-x-1 text-gray-500 hover:text-red-500">
                        <span>❤️</span>
                        <span>{item.likes}</span>
                      </button>
                      <button className="flex items-center space-x-1 text-gray-500 hover:text-blue-500">
                        <span>💬</span>
                        <span>{item.comments}</span>
                      </button>
                      <button className="flex items-center space-x-1 text-gray-500 hover:text-green-500">
                        <span>🔄</span>
                        <span>{item.shares}</span>
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SharePage;

// src/lib/components/Share.svelte
<script lang="ts">
  import Button from '$lib/components/ui/button/button.svelte'
  import Card from '$lib/components/ui/card/card.svelte'
  import CardContent from '$lib/components/ui/card/card-content.svelte'
  import CardHeader from '$lib/components/ui/card/card-header.svelte'
  import Avatar from '$lib/components/ui/avatar/avatar.svelte'
  import AvatarImage from '$lib/components/ui/avatar/avatar-image.svelte'
  import AvatarFallback from '$lib/components/ui/avatar/avatar-fallback.svelte'

  const shares = [
    {
      id: '1',
      user: {
        name: '张小明',
        username: 'zhangxiaoming',
        avatar: 'https://picsum.photos/seed/user1/50/50.jpg'
      },
      content: '今天吃了一顿超级美味的火锅！🍲 这个冬天太适合吃热腾腾的食物了。强烈推荐大家去试试这家店的麻辣锅底，简直是人间美味！',
      timestamp: new Date(Date.now() - 1000 * 60 * 2),
      likes: 15,
      comments: 3,
      media: ['https://picsum.photos/seed/share1/400/300.jpg'],
      type: 'status'
    },
    {
      id: '2',
      user: {
        name: '李美丽',
        username: 'limeili',
        avatar: 'https://picsum.photos/seed/user2/50/50.jpg'
      },
      content: '分享一下最近在读的一本书《代码大全》📚 里面有很多实用的编程技巧和最佳实践，推荐给所有开发者朋友阅读。#读书笔记 #编程学习',
      timestamp: new Date(Date.now() - 1000 * 60 * 5),
      likes: 8,
      comments: 2,
      type: 'status'
    },
    {
      id: '3',
      user: {
        name: '王大伟',
        username: 'wangdawei',
        avatar: 'https://picsum.photos/seed/user3/50/50.jpg'
      },
      content: '终于完成了自己的个人作品集网站！🎉 从设计到上线历时3个月，中间踩了不少坑但学到了很多。现在可以和大家分享我的作品了，欢迎大家参观指导！https://example.com',
      timestamp: new Date(Date.now() - 1000 * 60 * 8),
      likes: 42,
      comments: 18,
      type: 'status'
    }
  ]
</script>

<div class="max-w-4xl mx-auto p-6">
  <div class="mb-6">
    <h1 class="text-3xl font-bold text-gray-900 mb-2">分享</h1>
    <div class="flex space-x-4">
      <button class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">发布分享</button>
      <button class="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">我的分享</button>
      <button class="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">好友分享</button>
      <button class="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">热门分享</button>
    </div>
  </div>

  <div class="space-y-6">
    {#each shares as share (share.id)}
      <Card class="hover:shadow-lg transition-shadow">
        <CardContent class="p-6">
          <div class="flex space-x-4 mb-4">
            <Avatar class="h-12 w-12">
              <AvatarImage src={share.user.avatar} alt={share.user.name} />
              <AvatarFallback>{share.user.name[0]}</AvatarFallback>
            </Avatar>
            
            <div class="flex-1">
              <div class="flex items-center space-x-2">
                <span class="font-semibold text-gray-900">{share.user.name}</span>
                <span class="text-sm text-gray-500">@{share.user.username}</span>
                <span class="text-xs text-gray-500">•</span>
                <span class="text-xs text-gray-500">
                  {share.timestamp.toLocaleString('zh-CN', { 
                    month: 'long', 
                    day: 'numeric', 
                    hour: '2-digit', 
                    minute: '2-digit'
                  })}
                </span>
              </div>
            </div>
          </div>
          
          <div class="text-gray-900 leading-relaxed mb-4">{share.content}</div>
          
          {#if share.media && share.media.length > 0}
            <div class="grid grid-cols-1 md:grid-cols-2 gap-2 mb-4">
              {#each share.media as mediaUrl}
                <img 
                  src={mediaUrl} 
                  alt="分享图片"
                  class="w-full h-64 object-cover rounded-lg border"
                />
              {/each}
            </div>
          {/if}
          
          <div class="flex items-center justify-between text-sm">
            <div class="flex space-x-6">
              <button class="flex items-center space-x-1 text-gray-600 hover:text-blue-600">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path>
                </svg>
                <span>{share.comments}</span>
              </button>
              
              <button class="flex items-center space-x-1 text-gray-600 hover:text-green-600">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m9.032 4.026a9.001 9.001 0 01-7.432 0m9.032-4.026A9.001 9.001 0 0112 3c-4.474 0-8.268 3.12-9.032 7.326m9.032 4.026A9.001 9.001 0 012.968 10.326"></path>
                </svg>
                <span>分享</span>
              </button>
              
              <button class="flex items-center space-x-1 text-gray-600 hover:text-red-600">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
                </svg>
                <span>{share.likes}</span>
              </button>
            </div>
            
            <div class="flex space-x-2">
              <button class="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 text-sm">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 5a2 2 0 012-2h14a2 2 0 012 2 7 0l-4 4H5a2 2 0 00-2-2v14a2 2 0 00-2 2h-4a2 2 0 012-2v-8a2 2 0 00-2 2h4a2 2 0 012 2v-2a2 2 0 00-2-2h-4a2 2 0 00-2-2v8a2 2 0 00-2-2H7a2 2 0 00-2-2v-2a2 2 0 00-2-2h-4a2 2 0 00-2-2H5a2 2 0 00-2-2H3a2 2 0 00-2-2h-4a2 2 0 00-2-2h-4l-4 4a2 2 0 00-2-2 0z"></path>
                </svg>
                保存
              </button>
              <button class="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 text-sm">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 00-3 3h4a3 3 0 00-3 3v4a3 3 0 003 3h4a3 3 0 003 3v8a3 3 0 00-3-3h4a3 3 0 00-3 3h-4a3 3 0 00-3-3H7a3 3 0 00-3-3H4a3 3 0 00-3-3h-4a3 3 0 00-3-3v1a3 3 0 00-3-3H4a3 3 0 00-3-3H7a3 3 0 00-3-3z"></path>
                </svg>
                收藏
              </button>
            </div>
          </div>
        </CardContent>
      </Card>
    {/each}
  </div>

  <div class="mt-8 text-center">
    <button class="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
      加载更多分享
    </button>
  </div>
</div>
